### ISSUE TITLE
[BUG] Confirming Edge Effects

### ISSUE THREAD

**Issue by cmarshak** [dbekaert/RAiDER#387]
**Describe the bug**
There are edge effects when using the ray-tracing. This may be correct but might be worth explaining here to non-expert. Or it might have to do with interpolating 0s outside of the area of interest. Not sure.

Here is a screenshot of hydro @ 5000 meters in QGIS. All levels have this effect (see product below).

<img width="662" alt="image" src="https://user-images.githubusercontent.com/5975894/201191474-a3f14514-db88-48b5-b926-28695d38ee5b.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/5975894/201191593-10884631-c396-485c-96ae-486de8c0ac28.png">

Here is a [link](https://raider-development-tests.s3.us-west-2.amazonaws.com/ERA5_tropo_20211102T062159_std.nc) to the output cube.

**To Reproduce**
See #381 for details. Reproducing the yml file for clarity below:

```
look_dir: right

date_group:
  date_start:
  date_end:
  date_step:
  date_list:  [20211102]

time_group:
  time: "06:21:59"
  end_time:

weather_model: ERA-5

aoi_group:
  lat_file:
  lon_file:
  height_file_rdr:
  station_file:
  bounding_box: 53.0 56.0 -4.0 -1.0
  utm_zone:
  grid_x:
  grid_y:

height_group:
  dem:
  use_dem_latlon: False
  height_file_rdr:
  height_levels: "-500 0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000"

los_group:
  ray_trace: True  # Use projected slant delay by default
  zref: # Integration height. Only used in raytracing.
  los_file:
  los_convention: isce  # can be "isce" or "hyp3", see *** for details
  los_cube:
  orbit_file: S1B_OPER_AUX_POEORB_OPOD_20211122T112354_V20211101T225942_20211103T005942.EOF

runtime_group:
  verbose: True
  raster_format: nc # Can be any rasterio-compatible format
  output_directory: .
  weather_model_directory: weather_files
  cube_spacing_in_m: 2000.
  output_projection:  4326
```
