### ISSUE TITLE
[BUG] weather model bounds too small for larger grid sizes

### ISSUE THREAD

**Issue by bbuzz31** [dbekaert/RAiDER#518]
for a user input `cube_spacing_in_m` of 50000, the interpolators (weather model locations) do not fully cover the study area.
For the config file below,  buffer has to be increased in the far range

For HRRR, both the near range and far range (and possible y direction) need to be increased.

Note this should not affect GUNW workflow which uses a smaller (weather model dependent) `cube_spacing_in_m` 
```
aoi_group:
  bounding_box:
  - 33
  - 34
  - -118.25
  - -117.25
cube_spacing_in_m: '50000.0'
date_group:
  date_list: '20200130'
download_only: false
height_group:
  height_levels:
  - -500
  - 0
  - 500
  - 1000
look_dir: right
los_group:
  orbit_file: ./S1B_OPER_AUX_POEORB_OPOD_20210317T025713_V20200129T225942_20200131T005942.EOF
  ray_trace: true
time_group:
  interpolate_time: false
  time: '13:52:45'
weather_model: ERA-5
```
Download the orbit file with sentineleof `eof -d 20200130 -m S1B`
